export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';

export const POST_BOOK_REQUEST ='POST_BOOK_REQUEST';
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS';
export const POST_BOOK_FAIL = 'POST_BOOK_FAIL';