export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';

export const POST_BOOK_REQUEST ='POST_BOOK_REQUEST';
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS';
export const POST_BOOK_FAIL = 'POST_BOOK_FAIL';

export const EDIT_BOOK_REQUEST ='EDIT_BOOK_REQUEST';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAIL = 'EDIT_BOOK_FAIL';

export const DELETE_BOOK_REQUEST ='DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';