export const GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL';

export const POST_SERVICE_REQUEST = 'POST_SERVICE_REQUEST';
export const POST_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';
export const POST_SERVICE_FAIL = 'POST_SERVICE_FAIL';

export const EDIT_SERVICE_REQUEST = 'POST_SERVICE_REQUEST';
export const EDIT_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAIL = 'POST_SERVICE_FAIL';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';