export const GET_STAFF_REQUEST = 'GET_STAFF_REQUEST';
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS';
export const GET_STAFF_FAIL = 'GET_STAFF_FAIL';

export const POST_STAFF_REQUEST = 'POST_STAFF_REQUEST';
export const POST_STAFF_SUCCESS = 'POST_STAFF_SUCCESS';
export const POST_STAFF_FAIL = 'POST_STAFF_FAIL';

export const EDIT_STAFF_REQUEST = 'POST_STAFF_REQUEST';
export const EDIT_STAFF_SUCCESS = 'POST_STAFF_SUCCESS';
export const EDIT_STAFF_FAIL = 'POST_STAFF_FAIL';

export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAIL = 'DELETE_STAFF_FAIL';