export const GET_TYPE_REQUEST = 'GET_TYPE_REQUEST';
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS';
export const GET_TYPE_FAIL = 'GET_TYPE_FAIL';

export const POST_TYPE_REQUEST = 'POST_TYPE_REQUEST';
export const POST_TYPE_SUCCESS = 'POST_TYPE_SUCCESS';
export const POST_TYPE_FAIL = 'POST_TYPE_FAIL';

export const EDIT_TYPE_REQUEST = 'POST_TYPE_REQUEST';
export const EDIT_TYPE_SUCCESS = 'POST_TYPE_SUCCESS';
export const EDIT_TYPE_FAIL = 'POST_TYPE_FAIL';

export const DELETE_TYPE_REQUEST = 'DELETE_TYPE_REQUEST';
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL';

export const SELECT_TYPE = 'SELECT_TYPE';