export const GET_VOUCHER_REQUEST = 'GET_VOUCHER_REQUEST';
export const GET_VOUCHER_SUCCESS = 'GET_VOUCHER_SUCCESS';
export const GET_VOUCHER_FAIL = 'GET_VOUCHER_FAIL';

export const POST_VOUCHER_REQUEST = 'POST_VOUCHER_REQUEST';
export const POST_VOUCHER_SUCCESS = 'POST_VOUCHER_SUCCESS';
export const POST_VOUCHER_FAIL = 'POST_VOUCHER_FAIL';

export const EDIT_VOUCHER_REQUEST = 'POST_VOUCHER_REQUEST';
export const EDIT_VOUCHER_SUCCESS = 'POST_VOUCHER_SUCCESS';
export const EDIT_VOUCHER_FAIL = 'POST_VOUCHER_FAIL';

export const DELETE_VOUCHER_REQUEST = 'DELETE_VOUCHER_REQUEST';
export const DELETE_VOUCHER_SUCCESS = 'DELETE_VOUCHER_SUCCESS';
export const DELETE_VOUCHER_FAIL = 'DELETE_VOUCHER_FAIL';